title: "[Proposal]"
labels: [""]
body:
  - type: markdown
    attributes:
      value: |
        Explain what you would like to see improved
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: "What are you trying to accomplish"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: "Background information"
  - type: textarea
    id: success
    attributes:
      label: "Success criteria"
      description: "How would 'success' look to you? Milestones for this project"
 - type: textarea
    id: lookup
    attributes:
      label: Lookup
      description: "Relevant prior work or resources" 

